# The correct and final config.yml for the Netlify CMS setup
backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

# This new line enables the "submit for review" workflow
publish_mode: editorial_workflow

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    
    # This new line tells the CMS to save files in the correct format
    format: "yml-frontmatter"

    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price (UGX)", name: "price", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Category", name: "category", widget: "select", options: ["Electronics", "Fashion", "Home", "Vehicles", "Property", "Other"] }
      - { label: "Seller Name", name: "sellerName", widget: "string" }
      - { label: "Seller Phone", name: "sellerPhone", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["Approved", "Pending Review"], default: "Approved" }
      - { label: "Is Featured", name: "isFeatured", widget: "boolean", default: false, required: false }
      - { label: "Is Sponsored", name: "isSponsored", widget: "boolean", default: false, required: false }
      - { label: "Is Verified Seller product", name: "isVerified", widget: "boolean", default: false, required: false }
      - { label: "Is On Sale", name: "isOnSale", widget: "boolean", default: false, required: false }
