# The main configuration for your Netlify CMS
backend:
  name: git-gateway
  branch: main # Or 'master', depending on your main branch in GitHub

media_folder: "images/uploads" # Where uploaded images will be stored in your project
public_folder: "/images/uploads" # The public URL path to the images

collections:
  - name: "products" # The name of the collection
    label: "Products" # The name shown in the admin panel
    folder: "_products" # Saves each product as a file in a '_products' folder
    create: true # Allow users to create new products
    slug: "{{slug}}" # The filename for each product
    fields: # The fields for each product
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price (UGX)", name: "price", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Category", name: "category", widget: "select", options: ["Electronics", "Fashion", "Home", "Vehicles", "Property", "Other"] }
      - { label: "Seller Name", name: "sellerName", widget: "string" }
      - { label: "Seller Phone", name: "sellerPhone", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["Approved", "Pending Review"], default: "Approved" }
      - { label: "Is Featured", name: "isFeatured", widget: "boolean", default: false }
      - { label: "Is Sponsored", name: "isSponsored", widget: "boolean", default: false }
      - { label: "Is Verified Seller product", name: "isVerified", widget: "boolean", default: false }
      - { label: "Is On Sale", name: "isOnSale", widget: "boolean", default: false }
